name = "UVO_AET_AIO"
prefix = "uvo_aet_aio"
mainprefix = "z"

[properties]
author = "Antistasi Event Team - Nomas / Redwan S."
url = "https://github.com/Nomas-X/Unit-Voice-Overs-AET-AiO"

[binarize]
enabled = true # Default: true

[files]
include = [
    "mod.cpp",      # These files are copied to the build directory by default
    "meta.cpp",     # They do not need to be added to your list
    "LICENSE",
    "/img/*.paa",
    "logo_ca.paa",
    "logo_co.paa",
	"/assets/*.paa",
    "*.bikey"
]
exclude = [
    "*.psd",        # By default this list is empty
    "*.md",
    "/.vscode/",
]

[version]
path = "addons/main/script_version.hpp" # Default
# major = 0 # Overrides path when set
# minor = 1
# patch = 1
# git_hash = 4 # Default: 8




[hemtt.launch.default]
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "463939057",  # ACE3
    "2369477168", # Advanced Developer Tools
    "1779063631", # ZEN
]

dlc = []
optionals = []

parameters = [
    "-window",
    "-noPause",
    "-noPauseAudio",
]

[hemtt.launch.Altis]
extends = "default"
dlc = ["ws","rf"]
mission = "testMission.Altis"